name: "Database Migrations"

on:
  push:
    branches:
      - main

jobs:
  migrate-db:
    name: "Run Database Migrations"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: "Install Dependencies"
        run: pnpm install

      - name: "Run Migrations"
        run: pnpm db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
