name: CI - App View Counter

on:
  push:
    paths:
      - "package.json"
      - "bun.lock"
      - ".bun-version"
      - "turbo.json"
      - "packages/**"
      - "apps/view-counter/**"
      - ".github/workflows/ci-app-view-counter.yml"
  pull_request:
    paths:
      - "package.json"
      - "bun.lock"
      - ".bun-version"
      - "turbo.json"
      - "packages/**"
      - "apps/view-counter/**"
      - ".github/workflows/ci-app-view-counter.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - run: bun install --frozen-lockfile
      - run: bun run test --filter=view-counter
      - run: bun run build --filter=view-counter
