name: CI - Package Views Client

on:
  push:
    paths:
      - "packages/views-client/**"
      - ".github/workflows/ci-pkg-views-client.yml"
  pull_request:
    paths:
      - "packages/views-client/**"
      - ".github/workflows/ci-pkg-views-client.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: cd packages/views-client && bun test
